SELECT * FROM
(
SELECT
	PS.ID_PESSOA,
	TP.DT_REF,
	ROW_NUMBER() OVER(PARTITION BY TP.DT_REF ORDER BY PS.ID_PESSOA DESC) ORDEM

FROM f_Vendas VN 
LEFT JOIN d_Tempo TP ON VN.ID_TEMPO = TP.ID_TEMPO
LEFT JOIN d_Pessoa PS ON VN.ID_PESSOA = PS.ID_PESSOA
) T
WHERE T.ORDEM = 1